[versions]
agp = "8.13.1"
calendar = "2.3.1"
firebaseBom = "34.4.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
qrcodegen = "1.8.0"
recyclerview = "1.4.0"
firebaseAuth = "24.0.1"
navigationFragment = "2.9.5"
navigationUi = "2.9.5"
googleGmsGoogleServices = "4.4.4"
firebaseDatabase = "22.0.1"
playServicesMaps = "19.2.0"
transportApi = "4.0.0"
firebaseFirestore = "26.0.2"
firebaseMessaging = "25.0.1"

[libraries]
calendar = { module = "com.maxkeppeler.sheets:calendar", version.ref = "calendar" }
clock = { module = "com.maxkeppeler.sheets:clock", version.ref = "calendar" }
color = { module = "com.maxkeppeler.sheets:color", version.ref = "calendar" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
google-firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
qrcodegen = { module = "io.nayuki:qrcodegen", version.ref = "qrcodegen" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
transport-api = { group = "com.google.android.datatransport", name = "transport-api", version.ref = "transportApi" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
google-firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

